### ISSUE TITLE
Compiler loops infinitely

### ISSUE THREAD

**Issue by bluebear94** [breuleux/earl-grey#16]
[This is the file](http://pastebin.com/HdKKtanr) (pastebin for privacy reasons) that I'm trying to compile.

I just merged changes on my personal branch to master and entered `git checkout master` followed by `git pull`.

**Comment by breuleux** [comment]
I messed up DOS-style carriage returns with the lexer. None of the rules could recognize `\r`. I had a catch-all rule to grab a character and keep advancing, but well, `.` in a regular expression does not match `\r`. So it just looped in place. Even a file with a single `\r` character gives this behavior.

Yeah, that's pretty stupid. It is now fixed. Thanks for pointing it out.
