### ISSUE TITLE
Support usage of promisify in require

### ISSUE THREAD

**Issue by davej** [breuleux/earl-grey#20]
I have tons of boilerplate which could be moved to `require`, for example:

```
temp-open = promisify(temp.open)
fs-read = promisify(fs.read-file)
fs-write = promisify(fs.write)
fs-close = promisify(fs.close)
replace = promisify(replace-in-file)
nginx-conf-edit = promisify(nginx-conf.NginxConfFile.create)
```

@breuleux's suggestion: `require: fs -> (promisify! read-file, promisify! write)`

**Comment by breuleux** [comment]
`0.0.10` now allows `require: fs -> (promisify! read-file, promisify! write)`
