### ISSUE TITLE
% operator behavior does not match documentation

### ISSUE THREAD

**Issue by tomxtobin** [breuleux/earl-grey#34]
The `%` operator's behavior doesn't match [the documentation][docs].

The docs give this example:

```earlgrey
node =
   div#main %
      "Some text"
      strong % 1234
      a.large.red %
         href = "http://example.com"
         "stuff"

require: /html
html(node)
```

... which should result in this HTML:

```html
<div id="main">
  Some text
  <strong>1234</strong>
  <a class="large blue" href="http://example.com">stuff</a>
</div>
```

Instead, it results in this HTML:

```html
<main id="">
  Some text
  <strong>1234</strong>
  <a href="http://example.com" class="large red">stuff</a>
</main>
```

(**Edited to add:** Just to be clear, the chief problem here is that the `%` operator is fumbling `div#main` syntax. The blue/red difference is just a doc error, not a code error.)

[docs]: http://breuleux.github.io/earl-grey/doc.html#documentbuildingsyntax

**Comment by breuleux** [comment]
Yeah, I know, I've been lazy about fixing this. In the meantime, it'll work if you do `div[#main]`.
