### ISSUE TITLE
interpolation in single quotes vs double quotes

### ISSUE THREAD

**Issue by jots** [breuleux/earl-grey#39]
Is there a reason string interpolation is in single quotes instead of double quotes?
In ruby, perl and coffeescript it is the opposite (double quotes interpolate and single quotes don't).
Muscle memory is killing me on this :-)

**Comment by breuleux** [comment]
Originally I only had double quotes, and single quotes were used for something else. Then I changed that and this was just the easiest way to make it all work, given the existing code base. I agree it may have been more intuitive the other way around, but I think it's probably too late now.

**Comment by jots** [comment]
Ah that makes sense.  Well if you ever decide to change it to double quotes, you have my vote ;-)

**Comment by iki** [comment]
+1 for change before 1.0.0, any developer with some experience has this muscle memory and this breaks it

**Comment by breuleux** [comment]
I'll consider it, I'd just need to make a translation tool for all the code it'd break. That likely wouldn't be too difficult since it's just swapping the two quote types, and I could use that for other potential changes.
