### ISSUE TITLE
Tooling page is outdated.

### ISSUE THREAD

**Issue by bheesham** [breuleux/earl-grey#41]
Page: http://www.earl-grey.io/tooling.html

  - The link to earlmode.eg is broken.
  - earlmode.eg no longer exists in [repple](https://github.com/breuleux/repple/tree/master/src).

**Comment by breuleux** [comment]
Ah, yeah, I had moved it [over there](https://github.com/breuleux/quaint-repple/blob/master/src/earlmode.eg). Thanks for bringing this to my attention, I fixed the link.
