### ISSUE TITLE
How do I define an empty object literal?

### ISSUE THREAD

**Issue by davej** [breuleux/earl-grey#8]
I realise that I can use the constructor: `new Object()`.
But the object literal `{}` (in js) is much more quickly readable to me and also much more performant.

**Comment by davej** [comment]
Just realised that I can `let my-object = {=}` to get an object literal. Awesome, might be useful to document this because initialising object literals is quite common in javascript.

**Comment by breuleux** [comment]
I think I mention it in the interactive tutorial. Anyway, I added the information to the main documentation.
